// Generated by Selenium IDE và đã cấu hình tối ưu chạy trên Microsoft Edge
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestProject1
{
    [TestFixture]
    public class DefaultSuiteTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [SetUp]
        public void SetUp()
        {
            driver = new EdgeDriver();
            driver.Manage().Window.Maximize();

            // Tự động đợi tối đa 10 giây nếu Element chưa xuất hiện trong DOM
            driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }

        [TearDown]
        protected void TearDown()
        {
            if (driver != null)
            {
                driver.Quit();
                driver.Dispose();
            }
        }

        [Test]
        public void e2EBakeryPurchaseFlow()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(2000); // Chờ chuyển hướng về trang chủ sau khi login admin

            driver.FindElement(By.Id("categoryDropdown")).Click();
            driver.FindElement(By.LinkText("Bánh Sinh Nhật")).Click();

            Thread.Sleep(1000); // Đợi danh mục load sản phẩm

            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            driver.FindElement(By.CssSelector(".btn-cta")).Click(); // Thêm vào giỏ

            Thread.Sleep(1000); // Đợi hiệu ứng giỏ hàng cập nhật

            driver.FindElement(By.CssSelector(".cart-icon > .fas")).Click();
            driver.FindElement(By.LinkText("Tiến hành Thanh toán")).Click();

            Thread.Sleep(1000); // Đợi trang thanh toán hiển thị

            driver.FindElement(By.Id("CustomerName")).Click();
            driver.FindElement(By.Id("CustomerName")).Clear();
            driver.FindElement(By.Id("CustomerName")).SendKeys("Phạm Thanh Huy");
            driver.FindElement(By.Id("Address")).Click();
            driver.FindElement(By.Id("Address")).SendKeys("140 Lê Trọng Tấn");
            driver.FindElement(By.Id("Phone")).Click();
            driver.FindElement(By.Id("Phone")).SendKeys("123456789");
            driver.FindElement(By.CssSelector(".btn")).Click(); // Xác nhận đặt hàng

            Thread.Sleep(2000); // Chờ xử lý đơn hàng và chuyển sang trang cảm ơn

            Assert.That(driver.FindElement(By.CssSelector("h2")).Text, Is.EqualTo("Cảm ơn bạn!"));
            driver.FindElement(By.CssSelector("h2")).Click();
        }

        [Test]
        public void flow03CapNhatSoLuongGioHang()
        {
            // 1. Đăng nhập hệ thống
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(2000); // Đợi chuyển hướng an toàn về trang chủ

            // 2. Thêm sản phẩm vào giỏ
            driver.FindElement(By.LinkText("Tất Cả Sản Phẩm")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            Thread.Sleep(1000);
            driver.FindElement(By.CssSelector(".btn-cta")).Click(); // Thêm vào giỏ hàng

            Thread.Sleep(1500); // Chờ hiệu ứng giỏ hàng cập nhật xong số lượng badge

            // 3. Vào trang giỏ hàng
            driver.FindElement(By.CssSelector(".cart-icon > .fas")).Click();
            Thread.Sleep(1500); // Đợi trang giỏ hàng load xong hoàn toàn diện mạo

            // Kiểm tra tổng tiền ban đầu (1 sản phẩm)
            Assert.That(driver.FindElement(By.CssSelector(".cart-total")).Text, Is.EqualTo("Tổng Cộng: 120.000 VNĐ"));

            // 4. Thay đổi số lượng sang 3
            var quantityInput = driver.FindElement(By.Name("quantity"));
            quantityInput.Click();

            // Sử dụng JavaScript để thay đổi giá trị trực tiếp, chặn đứng việc ô bị rỗng kích hoạt AJAX lỗi
            js.ExecuteScript("arguments[0].value = '3';", quantityInput);
            Thread.Sleep(500);

            // Gửi phím Enter ngay tại ô nhập liệu để Form tự submit cập nhật (Thay vì đi click lung tung trúng nút thanh toán)
            quantityInput.SendKeys(Keys.Enter);

            // Chờ 2 giây cố định để trang web xử lý tính toán lại tiền và render lại giao diện
            Thread.Sleep(2000);

            // 5. Xác nhận lại tổng tiền mới (3 sản phẩm)
            Assert.That(driver.FindElement(By.CssSelector(".cart-total")).Text, Is.EqualTo("Tổng Cộng: 360.000 VNĐ"));
        }

        [Test]
        public void flow04DangKyThatBai()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng ký")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("Email")).SendKeys("abcd@gmail.com");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.Id("XacNhanMatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(2000); // Chờ server trả về kết quả lỗi trùng tên

            Assert.That(driver.FindElement(By.CssSelector(".validation-summary-errors li:nth-child(1)")).Text, Is.EqualTo("Name huypham is already taken."));
        }

        [Test]
        public void flow05DangKyThanhCong()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng ký")).Click();

            vars["randomUsername"] = js.ExecuteScript("return \"user\" + Math.floor(Math.random() * 10000);");
            driver.FindElement(By.Id("TenDangNhap")).SendKeys(vars["randomUsername"].ToString());

            vars["randomEmail"] = js.ExecuteScript("return \"test\" + Math.floor(Math.random() * 10000) + \"@gmail.com\";");
            driver.FindElement(By.Id("Email")).SendKeys(vars["randomEmail"].ToString());

            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.Id("XacNhanMatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(2500); // Chờ tạo tài khoản và tự động log-in chuyển hướng

            Assert.That(driver.FindElement(By.CssSelector(".user-menu-trigger")).Text, Is.EqualTo($"Chào, {vars["randomUsername"]}!"));
        }

        [Test]
        public void flow06DangNhapThatBai()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham1");
            driver.FindElement(By.Id("MatKhau")).SendKeys("1234567");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(1500); // Chờ hiển thị thông báo lỗi từ Validation Summary

            Assert.That(driver.FindElement(By.CssSelector(".validation-summary-errors li")).Text, Is.EqualTo("Tên đăng nhập hoặc mật khẩu không đúng."));
        }

        [Test]
        public void flow07XoaKhoiGioHang()
        {
            // Đăng nhập trước để đảm bảo thêm/xóa giỏ hàng nhất quán theo Session User
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Tất Cả Sản Phẩm")).Click();
            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            driver.FindElement(By.CssSelector(".btn-cta")).Click();

            Thread.Sleep(1000);

            driver.FindElement(By.Id("cart-count")).Click();
            driver.FindElement(By.LinkText("Xóa")).Click();

            Thread.Sleep(1500); // Chờ thao tác xóa sản phẩm bằng AJAX hoàn tất cập nhật badge số lượng

            Assert.That(driver.FindElement(By.Id("cart-count")).Text, Is.EqualTo("(0)"));
        }

        [Test]
        public void flow08ThanhToanThatBai()
        {
            // Đăng nhập để tiến hành vào trang checkout
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Tất Cả Sản Phẩm")).Click();
            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            driver.FindElement(By.CssSelector(".btn-cta")).Click();

            Thread.Sleep(1000);

            driver.FindElement(By.CssSelector(".cart-icon > .fas")).Click();
            driver.FindElement(By.LinkText("Tiến hành Thanh toán")).Click();

            Thread.Sleep(1000);

            driver.FindElement(By.Id("CustomerName")).Clear();
            driver.FindElement(By.Id("CustomerName")).SendKeys("Phạm Thanh Huy");
            driver.FindElement(By.Id("Address")).Clear(); // Để trống trường Address để kích hoạt lỗi validation
            driver.FindElement(By.Id("Phone")).SendKeys("0987654321");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(1000);

            Assert.That(driver.FindElement(By.CssSelector(".field-validation-error")).Text, Is.EqualTo("The Address field is required."));
        }

        [Test]
        public void flow09DangXuat()
        {
            // Phải đăng nhập thì mới có nút Đăng xuất để bấm
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Đăng xuất")).Click();

            Thread.Sleep(1500);

            Assert.That(driver.FindElement(By.LinkText("Đăng nhập")).Text, Is.EqualTo("Đăng nhập"));
        }

        [Test]
        public void flow10DangNhapThanhCong()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();

            Thread.Sleep(2000); // Chờ chuyển hướng hoàn tất

            Assert.That(driver.FindElement(By.CssSelector(".user-menu-trigger")).Text, Is.EqualTo("Chào, huypham!"));
        }

        [Test]
        public void flow11XemLichSuDonHang()
        {
            // Cần đăng nhập mới xem được lịch sử đơn hàng cá nhân
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("huypham");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Đơn hàng của tôi")).Click();

            Thread.Sleep(1000);

            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();

            Thread.Sleep(1000);

            Assert.That(driver.FindElement(By.CssSelector("h4:nth-child(3)")).Text, Is.EqualTo("Sản Phẩm Đã Mua"));
        }

        [Test]
        public void flow12LocSanPham()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Tất Cả Sản Phẩm")).Click();

            Thread.Sleep(1000); // Đợi danh sách sản phẩm load đầy đủ

            // 1. Chọn bộ lọc 1
            driver.FindElement(By.CssSelector("li:nth-child(2) > label")).Click();
            Thread.Sleep(1500); // Chờ danh sách sản phẩm render lại sau khi lọc lần 1

            Assert.That(driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .product-price")).Text, Is.EqualTo("120.000 VNĐ"));

            // 2. CLICK LẠI VÀO BỘ LỌC 1 ĐỂ TẮT NÓ ĐI
            driver.FindElement(By.CssSelector("li:nth-child(2) > label")).Click();
            Thread.Sleep(1500); // Chờ giao diện trả về trạng thái ban đầu (hoặc đợi DOM ổn định)

            // 3. Chọn bộ lọc thứ 2 (ở đây kịch bản cũ của bạn gọi là bộ lọc bổ sung nằm ở child thứ 4)
            driver.FindElement(By.CssSelector("li:nth-child(4) > label")).Click();
            Thread.Sleep(1500); // Chờ danh sách sản phẩm render lại sau khi lọc lần 2

            Assert.That(driver.FindElement(By.CssSelector(".col-lg-4:nth-child(1) .product-price")).Text, Is.EqualTo("520.000 VNĐ"));
        }

        [Test]
        public void searchCakeFlow()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Tất Cả Sản Phẩm")).Click();

            driver.FindElement(By.Id("searchInput")).Click();
            driver.FindElement(By.Id("searchInput")).SendKeys("Apple");

            Thread.Sleep(1500); // Chờ khung gợi ý (suggestion dropdown) hiển thị dạng AJAX công khai

            driver.FindElement(By.CssSelector(".suggestion-item:nth-child(1) .suggestion-name")).Click();

            Thread.Sleep(1500); // Chờ chuyển hướng sang trang chi tiết bánh Apple Pie

            Assert.That(driver.FindElement(By.CssSelector("h1")).Text, Is.EqualTo("Apple Pie Đặc Biệt"));
        }

        // =================================================================
        // KHU VỰC CÁC BÀI TEST ADMIN CHUYỂN ĐỔI, TỐI ƯU HÓA VÀ THÊM ĐỘ TRỄ
        // =================================================================

        [Test]
        public void adminFlow13_CapNhatThongTinCaNhan()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000); // Đợi load trang chủ sau đăng nhập

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Thông tin cá nhân")).Click();
            Thread.Sleep(1500); // Đợi load trang profile

            driver.FindElement(By.Id("Email")).Click();
            driver.FindElement(By.Id("Email")).Clear();
            driver.FindElement(By.Id("Email")).SendKeys("admin1@gmail.com");
            driver.FindElement(By.CssSelector(".btn:nth-child(1)")).Click(); // Nút cập nhật

            Thread.Sleep(2000); // Đợi lưu dữ liệu thành công
            driver.FindElement(By.CssSelector(".form-group:nth-child(6) > .col-md-10")).Click();
        }

        [Test]
        public void adminFlow14_ThemSanPhamMoi()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Sản Phẩm")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Thêm Sản Phẩm Mới")).Click();
            Thread.Sleep(1500);

            // Sinh tên ngẫu nhiên để không bao giờ bị trùng lặp khóa hoặc trùng dòng trong SQL
            string tenBanhMoi = "TEstCast " + new Random().Next(1000, 9999);

            driver.FindElement(By.Id("Name")).SendKeys(tenBanhMoi);
            driver.FindElement(By.Id("Price")).SendKeys("120000");

            // Xử lý chọn Dropdown
            var dropdown = driver.FindElement(By.Id("CategoryId"));
            dropdown.FindElement(By.XPath("//option[. = 'Bánh Cưới']")).Click();

            driver.FindElement(By.CssSelector(".btn")).Click(); // Bấm lưu tạo mới
            Thread.Sleep(2500); // Chờ server xử lý lưu và đẩy về trang danh sách

            // Xác nhận chiếc bánh với tên ngẫu nhiên vừa tạo đã xuất hiện công khai trên trang danh sách
            Assert.That(driver.PageSource, Does.Contain(tenBanhMoi));
        }

        // =================================================================
        // HỆ THỐNG TEST CASE ADMIN ĐÃ FIX LỖI 404 VÀ RANDOM EMAIL
        // =================================================================

        [Test]
        public void adminFlow15_XoaSanPhamVuaThem()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            // Vào quản lý và thêm sản phẩm mới
            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Sản Phẩm")).Click();
            Thread.Sleep(1500);
            driver.FindElement(By.LinkText("Thêm Sản Phẩm Mới")).Click();
            Thread.Sleep(1500);

            string tenBanhXoa = "TestXoaSP_" + new Random().Next(1000, 9999);
            driver.FindElement(By.Id("Name")).SendKeys(tenBanhXoa);
            driver.FindElement(By.Id("ImageUrl")).SendKeys("123");
            driver.FindElement(By.Id("Price")).SendKeys("120000");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2500); // Chờ lưu dữ liệu và điều hướng về bảng danh sách

            // Click nút xóa của sản phẩm vừa tạo trong bảng danh sách để nhảy sang trang xác nhận xóa
            var nutXoaCuaBanh = driver.FindElement(By.XPath($"//tr[contains(.,'{tenBanhXoa}')]//a[contains(@class,'btn-danger') or text()='Xóa']"));
            nutXoaCuaBanh.Click();
            Thread.Sleep(2000); // CHỜ ĐỢI: Trang xác nhận xóa (giống trong hình bạn gửi) load xong hoàn toàn
            Assert.That(driver.PageSource, Does.Contain("Bạn có chắc chắn muốn xóa sản phẩm này?"));

            // 2. Click vào nút "Xóa" màu đỏ trên trang (Thường là nút có class .btn-danger hoặc input loại submit)
            // Nếu Selector ".btn-danger" lỗi, bạn có thể đổi thành By.XPath("//input[@value='Xóa']") hoặc By.CssSelector("input.btn")
            driver.FindElement(By.CssSelector(".btn-danger")).Click();

            Thread.Sleep(2500); // Chờ xử lý xóa dưới SQL Server và quay về trang danh sách sản phẩm ban đầu

            // 3. Xác thực cuối cùng: Tên chiếc bánh đã chính thức bốc hơi khỏi danh sách
            Assert.That(driver.PageSource, Does.Not.Contain(tenBanhXoa));
        }

        [Test]
        public void adminFlow16_SuaTenSanPham()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Sản Phẩm")).Click();
            Thread.Sleep(2000); // Tăng lên 2 giây cho bảng sản phẩm đổ dữ liệu ra hoàn toàn
            var nutSuaDauTien = driver.FindElement(By.XPath("(//table//a[text()='Sửa'])[1]"));
            nutSuaDauTien.Click();

            Thread.Sleep(2000); // Chờ trang chỉnh sửa sản phẩm load form lên

            string tenSuaMoi = "RenameTest_" + new Random().Next(10, 99);
            var oInputName = driver.FindElement(By.Id("Name"));
            oInputName.Click();
            oInputName.Clear();
            oInputName.SendKeys(tenSuaMoi);

            driver.FindElement(By.CssSelector(".btn")).Click(); // Bấm nút Lưu cập nhật
            Thread.Sleep(2500); // Chờ server update SQL Server và load lại trang danh sách
            Assert.That(driver.PageSource, Does.Contain(tenSuaMoi));
        }

        [Test]
        public void adminFlow17_XemChiTietDonHang()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Đơn Hàng")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.CssSelector(".order-detail-header")).Click();
            Assert.That(driver.FindElement(By.CssSelector("h4")).Text, Does.Contain("Chi Tiết Đơn Hàng"));
        }

        [Test]
        public void adminFlow18_DoiTrangThaiDonHang()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Đơn Hàng")).Click();
            Thread.Sleep(1500);

            var statusElement = driver.FindElement(By.CssSelector(".order-card:nth-child(3) .order-status"));
            statusElement.Click();

            driver.FindElement(By.LinkText("Xem Chi Tiết")).Click();
            Thread.Sleep(1500);

            var dropdown = driver.FindElement(By.Name("status"));
            dropdown.FindElement(By.XPath("//option[. = 'Đang giao hàng']")).Click();

            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            // Quay lại trang danh sách đơn hàng qua Menu UI để check kết quả
            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Đơn Hàng")).Click();
            Thread.Sleep(1500);

            string trangThaiMoi = driver.FindElement(By.CssSelector(".order-card:nth-child(3) .order-status")).Text;
            Assert.That(trangThaiMoi, Is.EqualTo("Đang giao hàng"));
        }

        [Test]
        public void adminFlow19_QuanLyNhanVien_ThemVaSua()
        {
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Nhân Viên")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Tạo Nhân Viên Mới")).Click();
            Thread.Sleep(1500);

            // Tạo chuỗi ngẫu nhiên để gán cho Email và Tên Đăng Nhập tránh lỗi trùng dữ liệu
            int soNgauNhien = new Random().Next(1000, 9999);
            string tenNVMoi = "TestNV_" + soNgauNhien;
            string emailRandomMoi = "testnv_" + soNgauNhien + "@gmail.com";

            // 1. Kiểm tra Validation lỗi mật khẩu yếu (< 6 ký tự)
            driver.FindElement(By.Id("TenDangNhap")).SendKeys(tenNVMoi);
            driver.FindElement(By.Id("Email")).SendKeys(emailRandomMoi);
            driver.FindElement(By.Id("MatKhau")).SendKeys("123");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(1000);

            Assert.That(driver.FindElement(By.CssSelector(".field-validation-error")).Text, Is.EqualTo("Mật khẩu phải có ít nhất 6 ký tự."));

            // 2. Sửa lại nhập đúng mật khẩu để tạo thành công
            var oPass = driver.FindElement(By.Id("MatKhau"));
            oPass.Clear();
            oPass.SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2500); // Chờ DB lưu nhân viên mới và tự redirect về trang danh sách

            // 3. Tiến hành sửa Email của chính nhân viên vừa tạo (Dùng XPath định vị chính xác dòng)
            var nutSuaCuaNV = driver.FindElement(By.XPath($"//tr[contains(.,'{tenNVMoi}')]//a[contains(@class,'btn-warning') or text()='Sửa']"));
            nutSuaCuaNV.Click();
            Thread.Sleep(1500);

            var oEmail = driver.FindElement(By.Id("Email"));
            oEmail.Clear();
            string emailSuaNgauNhien = "update_" + soNgauNhien + "@gmail.com";
            oEmail.SendKeys(emailSuaNgauNhien);
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            // 4. Đăng xuất admin, lấy tài khoản nhân viên mới tạo đăng nhập kiểm tra phân quyền
            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Đăng xuất")).Click();
            Thread.Sleep(1500);

            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys(tenNVMoi);
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            Assert.That(driver.FindElement(By.CssSelector(".user-menu-trigger")).Text, Is.EqualTo($"Chào, {tenNVMoi}!"));
        }

        [Test]
        public void adminFlow20_QuanLyNhanVien_Xoa()
        {
            // Luồng độc lập: Tạo ra một nhân viên rác rồi tự xóa chính nó để test không bị gãy data
            driver.Navigate().GoToUrl("http://localhost:9025/");
            driver.FindElement(By.LinkText("Đăng nhập")).Click();
            driver.FindElement(By.Id("TenDangNhap")).SendKeys("admin");
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2000);

            // 1. Tạo nhân viên mẫu để chuẩn bị xóa (Qua UI để né lỗi 404)
            driver.FindElement(By.CssSelector(".user-menu-trigger")).Click();
            driver.FindElement(By.LinkText("Quản lý Nhân Viên")).Click();
            Thread.Sleep(1500);
            driver.FindElement(By.LinkText("Tạo Nhân Viên Mới")).Click();
            Thread.Sleep(1500);

            int maNgauNhien = new Random().Next(1000, 9999);
            string tenNVXoa = "TestDelete_" + maNgauNhien;
            string emailXoaRandom = "delete_" + maNgauNhien + "@gmail.com";

            driver.FindElement(By.Id("TenDangNhap")).SendKeys(tenNVXoa);
            driver.FindElement(By.Id("MatKhau")).SendKeys("123456");
            driver.FindElement(By.Id("Email")).SendKeys(emailXoaRandom);
            driver.FindElement(By.CssSelector(".btn")).Click();
            Thread.Sleep(2500); // Chờ server xử lý lưu và quay về trang danh sách

            // 2. Tìm đúng dòng của nhân viên có tên 'tenNVXoa' để nhấn nút xóa dữ liệu
            var nutXoaNhanVien = driver.FindElement(By.XPath($"//tr[contains(.,'{tenNVXoa}')]//a[contains(@class,'btn-danger') or text()='Xóa']"));
            nutXoaNhanVien.Click();
            Thread.Sleep(2000); // CHỜ ĐỢI: Trang xác nhận xóa (giống trong hình bạn gửi) load xong hẳn

            // =================================================================
            // ĐÃ SỬA: KIỂM TRA TEXT TRÊN BODY VÀ CLICK NÚT XÓA MÀU ĐỎ CỦA FORM
            // =================================================================

            // 1. Xác nhận dòng chữ hỏi xuất hiện trên trang View Delete Nhân Viên
            Assert.That(driver.PageSource, Does.Contain("Bạn có chắc chắn muốn xóa nhân viên này?"));

            // 2. Click vào nút "Xóa" màu đỏ trên giao diện (sử dụng class .btn-danger của Bootstrap)
            driver.FindElement(By.CssSelector(".btn-danger")).Click();

            Thread.Sleep(2500); // Chờ xử lý xóa dưới SQL và quay về trang danh sách ban đầu

            // 3. Xác thực cuối cùng: Tên nhân viên đã không còn tồn tại trong danh sách hiển thị
            Assert.That(driver.PageSource, Does.Not.Contain(tenNVXoa));
        }
    }
}